// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Buyer struct {
	ID           uuid.UUID
	FirstName    string
	LastName     string
	Email        string
	ProfileImage sql.NullString
	Password     string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Product struct {
	ID              uuid.UUID
	Name            string
	Images          []string
	Price           float64
	AmountAvailable int32
	Category        string
	Discount        int32
	VendorID        uuid.UUID
}

type Vendor struct {
	ID           uuid.UUID
	Name         string
	Email        string
	ProfileImage sql.NullString
	BannerImage  sql.NullString
	Description  sql.NullString
	Password     string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
