// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: order_item.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createOrderItem = `-- name: CreateOrderItem :exec
INSERT INTO order_item (id, order_id, product_id, vendor_id, quantity, price) 
VALUES($1, $2, $3, $4, $5, $6)
`

type CreateOrderItemParams struct {
	ID        uuid.UUID
	OrderID   uuid.UUID
	ProductID uuid.UUID
	VendorID  uuid.UUID
	Quantity  int32
	Price     float64
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) error {
	_, err := q.db.ExecContext(ctx, createOrderItem,
		arg.ID,
		arg.OrderID,
		arg.ProductID,
		arg.VendorID,
		arg.Quantity,
		arg.Price,
	)
	return err
}
