// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: product.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO product (id, name, images, price, amount_available, category, discount, vendor_id)
VALUES ($1, $2, $3, $4, $5, $6, 0, $7)
RETURNING id, name, images, price, amount_available, category, discount, vendor_id
`

type CreateProductParams struct {
	ID              uuid.UUID
	Name            string
	Images          []string
	Price           string
	AmountAvailable int32
	Category        string
	VendorID        uuid.UUID
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct,
		arg.ID,
		arg.Name,
		pq.Array(arg.Images),
		arg.Price,
		arg.AmountAvailable,
		arg.Category,
		arg.VendorID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		pq.Array(&i.Images),
		&i.Price,
		&i.AmountAvailable,
		&i.Category,
		&i.Discount,
		&i.VendorID,
	)
	return i, err
}
