// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: vendor.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const findVendorByEmail = `-- name: FindVendorByEmail :one
SELECT id, first_name, last_name, business_name, email, country, profile_image, banner_image, description, password, created_at, updated_at FROM vendor WHERE email = $1
`

func (q *Queries) FindVendorByEmail(ctx context.Context, email string) (Vendor, error) {
	row := q.db.QueryRowContext(ctx, findVendorByEmail, email)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.BusinessName,
		&i.Email,
		&i.Country,
		&i.ProfileImage,
		&i.BannerImage,
		&i.Description,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findVendorById = `-- name: FindVendorById :one
SELECT id, first_name, last_name, business_name, email, country, profile_image, banner_image, description, password, created_at, updated_at FROM vendor WHERE id = $1
`

func (q *Queries) FindVendorById(ctx context.Context, id uuid.UUID) (Vendor, error) {
	row := q.db.QueryRowContext(ctx, findVendorById, id)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.BusinessName,
		&i.Email,
		&i.Country,
		&i.ProfileImage,
		&i.BannerImage,
		&i.Description,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const registerVendor = `-- name: RegisterVendor :one
INSERT INTO vendor (id, first_name, last_name, business_name, email, country, password, created_at, updated_at)
VALUES($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, first_name, last_name, business_name, email, country, profile_image, banner_image, description, password, created_at, updated_at
`

type RegisterVendorParams struct {
	ID           uuid.UUID
	FirstName    string
	LastName     string
	BusinessName string
	Email        string
	Country      string
	Password     string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) RegisterVendor(ctx context.Context, arg RegisterVendorParams) (Vendor, error) {
	row := q.db.QueryRowContext(ctx, registerVendor,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.BusinessName,
		arg.Email,
		arg.Country,
		arg.Password,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.BusinessName,
		&i.Email,
		&i.Country,
		&i.ProfileImage,
		&i.BannerImage,
		&i.Description,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVendorBanner = `-- name: UpdateVendorBanner :one
UPDATE vendor SET banner_image = $1
WHERE id = $2
RETURNING banner_image
`

type UpdateVendorBannerParams struct {
	BannerImage sql.NullString
	ID          uuid.UUID
}

func (q *Queries) UpdateVendorBanner(ctx context.Context, arg UpdateVendorBannerParams) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, updateVendorBanner, arg.BannerImage, arg.ID)
	var banner_image sql.NullString
	err := row.Scan(&banner_image)
	return banner_image, err
}

const updateVendorDescription = `-- name: UpdateVendorDescription :one
UPDATE vendor SET description = $1
WHERE id = $2
RETURNING description
`

type UpdateVendorDescriptionParams struct {
	Description sql.NullString
	ID          uuid.UUID
}

func (q *Queries) UpdateVendorDescription(ctx context.Context, arg UpdateVendorDescriptionParams) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, updateVendorDescription, arg.Description, arg.ID)
	var description sql.NullString
	err := row.Scan(&description)
	return description, err
}

const updateVendorProfilePicture = `-- name: UpdateVendorProfilePicture :one
UPDATE vendor SET profile_image = $1
WHERE id = $2
RETURNING profile_image
`

type UpdateVendorProfilePictureParams struct {
	ProfileImage sql.NullString
	ID           uuid.UUID
}

func (q *Queries) UpdateVendorProfilePicture(ctx context.Context, arg UpdateVendorProfilePictureParams) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, updateVendorProfilePicture, arg.ProfileImage, arg.ID)
	var profile_image sql.NullString
	err := row.Scan(&profile_image)
	return profile_image, err
}
