// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: vendor.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const registerVendor = `-- name: RegisterVendor :one
INSERT INTO vendor (id, name, email, password)
VALUES($1, $2, $3, $4)
RETURNING id, name, email, profile_image, banner_image, description, password
`

type RegisterVendorParams struct {
	ID       uuid.UUID
	Name     string
	Email    string
	Password string
}

func (q *Queries) RegisterVendor(ctx context.Context, arg RegisterVendorParams) (Vendor, error) {
	row := q.db.QueryRowContext(ctx, registerVendor,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Password,
	)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.ProfileImage,
		&i.BannerImage,
		&i.Description,
		&i.Password,
	)
	return i, err
}
