-- +goose Up
ALTER TABLE vendor
ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
-- +goose Down
ALTER TABLE vendor
DROP COLUMN created_at,
DROP COLUMN updated_at;