-- +goose Up
ALTER TABLE buyer
ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
-- +goose Down
ALTER TABLE buyer
DROP COLUMN created_at,
DROP COLUMN created_at;