-- +goose Up
ALTER TABLE product
ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN description TEXT NOT NULL;
-- +goose Down
ALTER TABLE product
DROP COLUMN created_at,
DROP COLUMN updated_at,
DROP COLUMN description;
